import React, { useEffect } from "react";
import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children, title = "Manitas Creativas" }) => {
  useEffect(() => {
    const menu = document.querySelector("#menu");
  }, []);

  const handleMenu = () => {
    menu.classList.remove("-left-full");
    menu.classList.add("left-0");
  };
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className="bg-neutral-900 max-w-screen min-h-screen h-full text-white flex flex-col sm:flex-row items-center">
        <div className="lg:w-1/4 sm:w-64 sm:block ">
          <Navbar></Navbar>
        </div>
        <div className="sm:hidden">
          <div className="w-screen  flex justify-center h-12 items-center shadow-sm shadow-neutral-600">
            <button
              className="absolute h-12 w-12 inset-0  text-2xl text-red-300  grid place-items-center z-20"
              onClick={handleMenu}
            >
              <svg
                stroke="currentColor"
                fill="currentColor"
                strokeWidth="0"
                viewBox="0 0 512 512"
                height="1em"
                width="1em"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M32 96v64h448V96H32zm0 128v64h448v-64H32zm0 128v64h448v-64H32z"></path>
              </svg>
            </button>
            <h1 className="text-lg font-medium text-red-300 ">
              Manitas Creativas
            </h1>
          </div>
        </div>
        <div className="lg:px-10 px-5 py-7 sm:w-3/4 w-full text-center flex flex-col h-full items-center ">
          {children}
        </div>
      </div>
    </>
  );
};

export default Layout;
