import React from "react";
import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children, title = "Manitas Creativas" }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className="bg-neutral-900 max-w-screen min-h-screen h-full text-white flex b items-center">
        <div className="lg:w-1/4 w-64 ">
          <Navbar></Navbar>
        </div>
        <div className="lg:px-10 px-5 py-7 w-3/4 text-center flex flex-col h-full items-center ">
          {children}
        </div>
      </div>
    </>
  );
};

export default Layout;
